dist: xenial
sudo: required

language: go

arch:
  - amd64
  - ppc64le
go: 
 - 1.15.6

install:
  - make goget-tools
script:
  - lsb_release -a
  - export PATH="$PATH:$GOPATH/bin"
  - make bin
  - make validate
  - make test-coverage
