dist: xenial
sudo: required

language: go

arch:
  - ppc64le
go: 
 - 1.15.6

install:
  - make goget-tools
script:
  - lsb_release -a
  - export PATH="$PATH:$GOPATH/bin"
  - make bin
  - make validate
  - make test-coverage

- <<: *base-test
      stage: test
      name: "devfile catalog, url, watch, push, debug, delete, exec, test, log, status, storage and create command integration tests on kubernetes cluster"
      env:
        - MINIKUBE_WANTUPDATENOTIFICATION=false
        - MINIKUBE_WANTREPORTERRORPROMPT=false
        - MINIKUBE_HOME=$HOME
        - CHANGE_MINIKUBE_NONE_USER=true
        - KUBECONFIG=$HOME/.kube/config
      before_script:
        # Download kubectl, a cli tool for accessing Kubernetes cluster
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.16.1/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download minikube and set up Kubernetes single node cluster
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.11.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch $KUBECONFIG
        - sudo minikube start --vm-driver=none --kubernetes-version=v1.16.1
        - "sudo chown -R travis: /home/travis/.minikube/"
        - sudo apt-get -qq update
        - sudo apt-get install -y socat
      script:
        - kubectl cluster-info
        - make bin
        - sudo cp odo /usr/bin
        - export KUBERNETES=true
        - travis_wait make test-cmd-project
        - travis_wait 60 make test-integration-devfile
